apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-serving
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-serving
  template:
    metadata:
      labels:
        app: mlflow-serving
    spec:
      containers:
        - name: mlflow-serving
          image: ghcr.io/mlflow/mlflow:v3.8.1
          ports:
            - containerPort: 5001
          command: ["mlflow"]
          args:
            - models
            - serve
            - -m
            - "models:/telco_churn_rf/latest"
            - --host
            - "0.0.0.0"
            - --port
            - "5001"
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-serving
  namespace: mlflow
spec:
  selector:
    app: mlflow-serving
  ports:
    - port: 5001
      targetPort: 5001

